### ISSUE TITLE
Add a missing webhooks use case to the project Wiki

### ISSUE THREAD

**Issue by marksto** [wdhowe/telegrambot-lib#102]
**Is your feature request related to a problem? Please describe.**
Missing documentation.

**Describe the solution you'd like**
Add a page under the project Wiki that describes the [webhooks](https://core.telegram.org/bots/api/#getting-updates) usage.

Underline the main idea from the official Telegram Bot API documentation:
_"Regardless of which option you choose, you will receive JSON-serialized [Update](https://core.telegram.org/bots/api/#update) objects as a result."_

An example code with [Compojure](https://github.com/weavejester/compojure):
```
(ns grossbuchbot.web-handler
  (:require [compojure.core :as cmpj :refer [POST]]
            [ring.middleware
             [defaults :as rmd]
             [json :refer [wrap-json-body wrap-json-response]]]
            <other requirements like `config` or `log`>))

...

;; NB: The main fn for an incoming `Update` object processing.
(defn handle [update]
  (log/debug "Received update:" update)
  <handle the update and return some `op-result`>)

...

(def api-routes
  (cmpj/context "/api" []
    (POST "/:token" {{token :token} :route-params
                     update :body}
      (if (= token (config/get-prop :bot-api-token))
        (let [op-result (handle update)]
          <translate the `op-result` to a response map>)
        <return a `404` response map>))))

...

(cmpj/defroutes
  app-routes

  (-> (rmd/wrap-defaults api-routes rmd/api-defaults)
      (wrap-json-body {:keywords? true})
      (wrap-json-response))

  <other web app routes>)
```

Then use the `app-routes` as a (part of) Ring-compatible web handler for your web app.

**Describe alternatives you've considered**
None.

**Additional context**
A reaction to the latest [Morse issue](https://github.com/Otann/morse/pull/59).

**Comment by marksto** [comment]
@wdhowe Hi Bill! How is it going? Just spot the fact that we didn't document an important use case — receiving updates through a preset webhook's update handler. Should we cover this one, shouldn't we?

**Comment by wdhowe** [comment]
Good call.

I renamed the "How To" wiki page to "Getting and Sending Messages".

Examples were added for polling and webhooks, using your snippet in this issue.

https://github.com/wdhowe/telegrambot-lib/wiki/Getting-and-Sending-Messages/820acab4c9e5a89b2fea95ed3bdcb988c102b5b5

**Comment by wdhowe** [comment]
@marksto Let me know if you think any further changes should be made to it. If not, I will resolve this issue.

**Comment by marksto** [comment]
@wdhowe Hi Bill! Everything looks fine, but it feels like you'r missing a `ns` declaration with requires for `status` and `fields`. I guess these are from your own projects, thus require special knowledge. Probably, it's better to abstract them away via empty fns and/or pseudo-code blocks (like I did in the snippet above with e.g. `<translate the `op-result` to a response map>`).

**Comment by wdhowe** [comment]
Good points, I'll clean that up.

**Comment by wdhowe** [comment]
These ambiguous calls have been cleaned up. Resolving this issue.
