### ISSUE TITLE
logging dependency qos.logback added to clojars artefact repo

### ISSUE THREAD

**Issue by awb99** [wdhowe/telegrambot-lib#109]
On https://clojars.org/telegrambot-lib we see that telegram bot lib has a dependency to:
[ch.qos.logback/logback-classic 1.2.11](http://search.maven.org/#artifactdetails%7Cch.qos.logback%7Clogback-classic%7C1.2.11%7Cjar)

But in project.clj we see:
 :project/dev {:dependencies [[ch.qos.logback/logback-classic "1.2.11"]]

==> this dependency is a DEV only dependency. It should NOT be in the clojars artefact.

Why is this important?
It means lots of warning messages in apps that use telegrambot-lib, but that do not provide config for qos.logback
(there are man logging libs out there; an app does not have to need to use qos.logback).

**Comment by wdhowe** [comment]
Interesting, I agree.

Looks like logback-classic was **not** included in 1.0.0 (pushed Jul 19, 2021): https://clojars.org/telegrambot-lib/versions/1.0.0

The first inclusion of logback-classic in the clojars artifacts was with 1.1.0 (pushed Nov 6, 2021): https://clojars.org/telegrambot-lib/versions/1.1.0

I'm not seeing any change in the project.clj that would have caused this.

The pom.xml didn't start getting included until Jan 7, 2022.

I built the pom and excluded the dev profile (lein with-profile -dev pom) in this change: #111

I will attempt to deploy to clojars by excluding the dev profile and see if that does it.

**Comment by wdhowe** [comment]
Looks like that worked:

`lein with-profile -dev deploy clojars`

https://clojars.org/telegrambot-lib/versions/2.0.0

Not sure why dev profiles are being included with pom files by default now.

**Comment by awb99** [comment]
Thanks a lot!!!
Perhaps you dont realize the scope of this problem. But it is HUGE. 
I can exclude one dependency in an app. But this does not help me when I use it in another library.
But it gets worse: There is  a logging config file in the jar (I should say it WAS). And this means it is trying to
configure it...

MANY THANKS!!!!
