### ISSUE TITLE
Cannot create a webhook using custom certificate

### ISSUE THREAD

**Issue by yokalona** [wdhowe/telegrambot-lib#128]
**Describe the bug**
According to telegram docs about https://core.telegram.org/bots/api#inputfile and https://core.telegram.org/bots/api#setwebhook 
the certificate has to be send as a regular file with mime/type **multipart/form-data**

Currently, I don't see any obvious ways to do that using only telegrambot-lib

**To Reproduce**
I'm trying to create hook using this code:
`(tb/set-webhook bot hook-url
                    {:secret_token secret-token
                     :certificate (slurp "/home/epb/epb-selfsigned.pem")})`

The result is:
`{:ok true, :result true, :description "Webhook was set"}`

But 

`(tb/get-webhook-info bot)`

returns:
`{:ok true, :result {:url "XXX", :has_custom_certificate false, :pending_update_count 11, :last_error_date 1684653461, :last_error_message "SSL error {error:0A000086:SSL routines::certificate verify failed}", :max_connections 40, :ip_address XXXX}}`

**Expected behavior**
A webhook is not only set, but a :has_custom_certificate flag is also set:

**Screenshots**

**Details (please complete the following information):**
[telegrambot-lib "2.6.0"] 
 I've tried:

`(tb/set-webhook bot {:url "XXXX" :ip_address "XXXX" :certificate (java.io.FileInputStream. "/Users/xxxx/e.pem")})`

and 

`(tb/set-webhook bot hook-url {:secret_token secret-token :certificate (slurp "/home/epb/epb-selfsigned.pem")})`

**Comment by yokalona** [comment]
As a workaround:
`curl -F "url=https://XXX" -F "certificate=@<CERT_PATH>.pem" -F "secret_token=XXX" https://api.telegram.org/bot<TOKEN>/setWebhook`

**Comment by wdhowe** [comment]
Documenting some notes while troubleshooting this:

- The current http/request assumes json content type.
- The different ways to send a request are: url query string, x-www-form-urlencoded, json, multipart/form-data. https://core.telegram.org/bots/api#making-requests
  - The above resource notes that multipart should be used for sending files, which we are trying to do with setting a webhook, so the current http/request implementation will not work for this.

Some tests
- Generated a self signed cert

```bash
openssl req -newkey rsa:2048 -sha256 -nodes -keyout telegrambot-lib.key -x509 -days 365 -out telegrambot-lib.pem -subj "/C=US/ST=STATEHERE/L=CITYHERE/O=Company/CN=put.ip.address.here"
```

- Opened a repl in telegrambot-lib.core

```clojure
;; required clj-http.client directly to work around current json content type
(require '[clj-http.client :as clj-http])

;; create a new bot
(def tbot (create "MYBOTTOKENHERE"))

;; Set the webhook using multipart
(clj-http/post (format "%s%s/%s" "https://api.telegram.org/bot" (:bot-token tbot) "setWebhook")
               {:multipart [{:name "certificate" :content (clojure.java.io/file "telegrambot-lib.pem")}
                            {:name "url" :content "https://put.ip.address.here"}]})

;; Verify
(get-webhook-info tbot)
{:ok true,
 :result
 {:url "https://put.ip.address.here",
  :has_custom_certificate true,
  :pending_update_count 1,
  :max_connections 40,
  :ip_address "put.ip.address.here"}}
```

So, I will need to make updates to send a multipart post request under certain conditions (file upload) OR consider using multipart posts for all requests instead of json.

Examples of other commands:

```clojure
;; no content/params
(clj-http/post (format "%s%s/%s" "https://api.telegram.org/bot" (:bot-token tbot) "getMe"))

;; content/params
(clj-http/post (format "%s%s/%s" "https://api.telegram.org/bot" (:bot-token tbot) "sendMessage")
               {:multipart [{:name "chat_id" :content "123456789"}
                            {:name "text" :content "Greetings, human."}]})
```

**Comment by wdhowe** [comment]
@yokalona - The newly released [2.8.0](https://github.com/wdhowe/telegrambot-lib/releases/tag/2.8.0) version should resolve this webhook set issue. Thank you for reporting it!

**Comment by marksto** [comment]
@wdhowe Hi Bill, it's been a while now! Apparently, It's now pretty obvious that switching the format of all API calls from JSON to multipart was not the best idea. =)
I would like to suggest reverting the default format of all API requests (except the two mentioned above) to JSON, with the option to switch to a multipart format when needed.
This should cover all cases mentioned in #139. I can provide a PR with this change, if you don't mind.

**Comment by wdhowe** [comment]
> @wdhowe Hi Bill, it's been a while now! Apparently, It's now pretty obvious that switching the format of all API calls from JSON to multipart was not the best idea. =)
> I would like to suggest reverting the default format of all API requests (except the two mentioned above) to JSON, with the option to switch to a multipart format when needed.
> This should cover all cases mentioned in #139. I can provide a PR with this change, if you don't mind.

Hi Mark, that's fine if you would like to put something together. I won't have time to take a look until after this weekend.
