### ISSUE TITLE
Multipart content cannot be nil

### ISSUE THREAD

**Issue by filipencopav** [wdhowe/telegrambot-lib#139]
**Describe the bug**
`tbot/get-updates` throws an error when you pass it `{:offset nil}`.

This is a problem, because in [your wiki](https://github.com/wdhowe/telegrambot-lib/wiki/Getting-and-Sending-Messages), you recommend people first set `offset` to nil, and then pass that (initially) nil variable in the map here:

```clojure
(defn poll-updates
  ([bot] (poll-updates bot ,,,nil,,,)) ; look here, WTF?
  ([bot ,,,offset,,,]
   (let [resp (tbot/get-updates bot {:offset ,,,offset,,,
                                     :timeout (:timeout config)})]
    ;; --snip--
```

Also, either convert all of your parameters from the map into strings, or tell the users that they can't be integers!
If I get the error: `Unsupported type for multipart content: class java.lang.Long`, from `clj-http`, I don't understand what's happening and what's wrang. Either catch the error and throw a new one, or write a spec with only string/file/etc. params.

The bug happens [here](https://github.com/wdhowe/telegrambot-lib/blob/1d2ff514312db3acd54e18e9dae44dc182c324a9/src/telegrambot_lib/http.clj#L110), because you encode to multipart by default. Add an option to encode JSON by default for users. Also, add a spec, and announce users in the wiki, that for `(get-updates ...)` to work, they need to encode all the parameters into strings (unless they're files etc.)

**To Reproduce**
```clojure
(def bot (tbot/create (:bot-token (edn/read-string (slurp "config.edn")))))
(tbot/get-updates bot {:offset 1})   ; to get «Unsupported type for multipart content: class java.lang.Long»
(tbot/get-updates bot {:offset nil}) ; to get «Multipart content cannot be nil»
```

**Expected behavior**
Works with nil (checks if nil and doesn't include), works with numbers (checks if number and encodes to string), works with everything that is in a map and is expected intuitively to work

**Details:**
 - Telegrambot-lib Version [e.g. 2.9.0]
 - Your code: No, example is enough.

**Additional context**
See #128 for the «fix» which introduced this bug.

[No up-to-date documentation?](https://i.imgflip.com/62iupl.jpg)

**Comment by steakoverflow-me** [comment]
Same here:

```
(defn api-wrap
  [api-f & args]
  (log/debug (format "Calling (%s %s)" api-f (str/join " " args)))
  (let [resp (apply api-f args)
        ok (:ok resp)
        desc (:description resp)]
    (when (not ok)
      (throw (ex-info "API response error" {:call api-f
                                            :description desc
                                            :response resp})))
    (log/debug (format "%s response is OK: %s" api-f desc))
    (:result resp)))
```

`(api-wrap telegrambot-lib.core/send-message (bot) {:chat_id (:id user)
                                                                 :text (:text msg)})`

In logs something like this:

> Calling (telegrambot_lib.api.methods$send_message@45895a98 {:bot-token "<secret>", :async false, :bot-api 

> "http://127.0.0.1:8899/test-api/"} {:chat_id 10000000, :text "Hello, bot!"})
> ...
> Fri Oct 13 23:47:16 IST 2023 [worker-1] ERROR - POST /
> clojure.lang.ExceptionInfo: API response error {:call #object[telegrambot_lib.api.methods$send_message 0x45895a98 "telegrambot_lib.api.methods$send_message@45895a98"], :description nil, :response {:error #error {
>  :cause "Unsupported type for multipart content: class java.lang.Integer"
>  :via
>  [{:type java.lang.Exception
>    :message "Unsupported type for multipart content: class java.lang.Integer"
>    :at [clj_http.multipart$eval11497$fn__11498 invoke "multipart.clj" 29]}]
>  :trace .........

**Comment by filipencopav** [comment]
@steakoverflow-me, while the author replies, you can use the function below for interacting with the api. The library doesn't offer much anyway -- it's just this code wrapped in some convenience functions.

```clojure
(require '[clj-http.client :as client]
         '[cheshire.core :as json])

(defn request [bot api-method params]
  (let [url (format "https://api.telegram.org/bot%s/%s" (:bot-token bot) api-method)
        response (client/post url {:content-type :json, :body (json/encode params)})]
    (-> response :body (json/decode true))))

(request {:bot-token "urtoken"} "getMe" {})
```
