### ISSUE TITLE
Add customs headers to Telegram API requests.

### ISSUE THREAD

**Issue by aldebogdanov** [wdhowe/telegrambot-lib#154]
Hello! Thank you again for the library 🙏🏼 

### What happened?
I am mocking Telegram API server for integration testing purposes. And I want seamless mulog traces from my Bot server to mock API server and back.

### Idea
Pass mulog's local context with headers in HTTP requests.

### Solution
Related pull request

**Comment by algoflora** [comment]
But I cannot push anything :(
