### ISSUE TITLE
documentation - unreleased changes for 1.0.0

### ISSUE THREAD

**Issue by wdhowe** [wdhowe/telegrambot-lib#74]
Document unreleased changes for 1.0.0 in the main readme:

- sync vs async bot messages
  - #72
  - #73
- logging config
  - #77
- json parser config
  - #79

This should follow the current "getting started" with examples pattern to get a developer up and going with the library.

**Comment by marksto** [comment]
Add a side note on a possible `clj-http` dependency version conflicts and how to resolve them. (?)
