### ISSUE TITLE
Elude library dependencies

### ISSUE THREAD

**Issue by marksto** [wdhowe/telegrambot-lib#76]
Hi Bill,

Here are my thoughts on how to prepare the library for the major release (#75) in regrads to its dependencies.
At the moment, some of them are implicit, unnecessary and possibly resulting in dependency versions conflicts.

Here's what can and should be done:

 - `cheshire`
   - set the `:provided` scope, leave it as `dev` profile dependency
   - implement as a choice of predefined options:
     - `cheshire`, `jsonista`, and `data.json` are supported
     - with runtime checks alike those in `clj-http.client` sources
   - document this
   - (optionally) add an ability to plug-in custom JSON parser via multi-method

 - `clj-http`
   - just set the `:provided` scope (to avoid possible versions conflicts like [this one](https://github.com/Otann/morse/issues/55))
   - leave it as `dev` profile dependency
   - document this

- `timbre`
  - as a _specific logger implementation_ should be substituted w/ the [logging facade](https://github.com/clojure/tools.logging)
  - then it is up to user which implementation to provide and what logging level to set up for "telegram-bot.lib"

Again, this is just a draft plan — to start the discussion up before I push any PRs. Any thoughts?

Cheers,
Mark

**Comment by wdhowe** [comment]
Interesting, I didn't know about lein :provided profiles before.

What does the burden look like for the bot developer for each of these?

These do sound like a good ideas, just want to have a clear picture.

I assume for the json library and clj-http library, they would just need to go into someone's normal dependency vector?

**Comment by marksto** [comment]
> for the json library and clj-http library, they would just need to go into someone's normal project dependency vector

Yep. That's basically what I've proposed above.

Or, there is another way — of `:exclude`-ing certain unnecessary dependencies. That's actually how the `clj-http` team approached this before the `2.x.x` version of their lib.

Of course, we have to mention that in the project README in both cases.

**Comment by marksto** [comment]
Ok, I think I know where's the "middle ground" we can hit.

- `cheshire`
  - making it optional (`:provided`), since, well, optional for the project in its essence
  - putting "bring your own JSON parser" in docs (1 of 3 common options)
  - adding runtime checks alike those in `clj-http.client` sources

- `clj-http`
  - leaving as is, since it's a mandatory dependency for the project
  - mentioning possible version conflicts in docs and advising to try to `:exclude`/update version in that case

- `timbre`
  - just swapping with a logging facade, usual thing to do for any library
 
Hope this now looks & feels less backbreaking for the end user.

Waiting for your confirmation, Bill, to do the job.

**Comment by wdhowe** [comment]
That sounds good to me. Wanting to follow common patterns, but not create too much setup work for the user.

**Comment by wdhowe** [comment]
This issue has been resolved with PRs:

- #77
- #79
