### ISSUE TITLE
Introduce connection pooling capabilities

### ISSUE THREAD

**Issue by marksto** [wdhowe/telegrambot-lib#81]
Hi Bill!

It makes sense to augment the bot `create` fn to add the connection pooling capabilities. We do not use one at the moment, but we should. Not only will it help improve performance and resource utilization efficiency, but it will also allow us/end user to fine tune the whole thing (sync/async, connect timeout, # of threads, etc.).

What I think should be possible:
- [ ] by default (no parameters are passed):
  - [ ] if there is already a bound `clj-http.conn-mgr/*connection-manager*`, do nothing
  - [ ] otherwise, create a synchronous connection pool manager with a default configuration
- [ ] if the `:async` parameter is passed and its value is `true`:
  - [ ] if there is already a bound `clj-http.conn-mgr/*async-connection-manager*`, do nothing
  - [ ] otherwise, create an asynchronous connection pool manager with a default configuration
- [ ] if the `:conn-mngr-opts` parameter is passed, use its value to configure a connection pool manager upon its creation
- [ ] if the `:conn-mngr` parameter is passed, use its value as a connection pool manager (it should be possible for an end user to provide their own connection pool manager)

The original incentive for this feature request is current inability to even pass a timeout for the underlying HTTP connection. When one requests to `get-updates` there is a `timeout` method parameter to pass along to the Bot API server, but there is no such option for any other method. This causes some requests to hang for tens of seconds...

@wdhowe, any thoughts on this feature? I propose to leave it up to `1.x.0`.

**Comment by marksto** [comment]
Here's what I usually get in the situation described above: 
```
started at 1626605380574
...
2021-07-18T10:50:55.934Z UnknownHost INFO [org.apache.http.impl.execchain.RetryExec:97] - I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://api.telegram.org:443: No route to host (Host unreachable)
2021-07-18T10:50:55.935Z UnknownHost INFO [org.apache.http.impl.execchain.RetryExec:113] - Retrying request to {s}->https://api.telegram.org:443
finished at 1626605456157
full round in 75583 ms
```
And this exception is sporadic. Usually everything is fine and you won't get one for the same request. The request (this one was for "editMessageText" API method) itself is synchronous (and it should be) and it leads to a noticeable drag in the UI.

**Comment by wdhowe** [comment]
Connection pooling is a good idea. I agree that being able to specify a http timeout is a needed feature.

Reference link to clj-http's docs on this subject: https://github.com/dakrone/clj-http#user-content-persistent-connections

Your proposed flow of options makes sense to me.

We will want to ensure that this new feature does not impose any new requirements for the library user to do anything except "(tbot/create)" unless they want to specify the advanced options.

**Comment by marksto** [comment]
Hi Bill!

Over these years I never actually required this feature, since it is possible to set these connection managers globally with:
```
(alter-var-root #'clj-http.conn-mgr/*connection-manager*
                (constantly (clj-http.conn-mgr/make-reusable-conn-manager {...})))
(alter-var-root #'clj-http.conn-mgr/*async-connection-manager*
                (constantly (clj-http.conn-mgr/make-reusable-async-conn-manager {...})))
```

or temporarily (for a particular API method call) with:
```
(binding [clj-http.conn-mgr/*async-connection-manager* ...]
  ...)
(binding [clj-http.conn-mgr/*connection-manager* ...]
  ...)
```

That said, the only thing that can be improved here is **the project Wiki** that I don't know how to contribute to.

Closing this enhancement proposal now.
